Editor plugin gets dynamic CONFIG
Ragzouken/bipsi pull request #7
Opened 2023-07-19 06:08 UTC by jon-heard

First, I apologize for bringing an update to this editor plugin system so soon after launch.

-- The problem:
When submitting to bipsi-hacks, Sean pointed out that changes to an editor plugin's settings aren't applied until the page is refreshed.  This is because CONFIG is created at plugin setup, and doesn't update to match settings changes.

-- The solutions:
After consideration, I came up with two solutions.  This is one of them, and [here](https://github.com/Ragzouken/bipsi/pull/6) is the other.  The other is simpler, but I prefer this one as it's simpler for the plugin developer.

-- Specifics:
The other solution provides the plugin with it's event id, forcing the plugin's editor code to "find" its event whenever it wants to read user-settings.  Meanwhile, the non-editor code relies on CONFIG for the settings, as it's always done.

**This** solution sets up CONFIG to be dynamic for the editor code; to always have the latest settings.  In this way, the plugin's editor code can use CONFIG, just like the non-editor code does.

2023-07-19 12:00 UTC, jon-heard commented
I'm attaching the latest version of the "fullscreen" plugin.  It is designed to work with this pull request.  To try it, use the fullscreen hotkey as normal and note that it works, then change the plugin's "fullscreen-hotkey" field to something like "Home" or "Backspace" and try it again, WITHOUT refreshing the webpage.  The new hotkey should effect take immediately.

[editor fullscreen.txt](https://github.com/Ragzouken/bipsi/files/12094616/editor.fullscreen.txt)

2023-07-23 13:06 UTC, Ragzouken requested changes
this seems acceptable, aside from the change i requested

2023-07-23 13:06 UTC, Ragzouken commented on src/scripts/maker.js
this class shouldn't know about the editor or plugins, so you should be able to replace these calls with on in the editor's listener for `this.stateManager`'s `change` event (somewhere around line ~1530). that's where everything gets updated when there's a state change

2023-07-23 16:09 UTC, jon-heard commented on src/scripts/maker.js
I've made this requested change

2023-07-23 16:17 UTC, jon-heard commented
I've made the requested change.  In addition:

- There is an edge case where the user either repeatedly hits undo to before loading the event or deletes the event, then hits undo or redo, where the event is still deleted.  I've adjusted how this is handled.  Previously, the config settings are cleared to defaults in this scenario.  Now, the config settings remain at what they were when the event was last available.
- I've moved the config-handling logic into BipsiEditor, since it's all dealing with BipsiEditor.editorPluginConfigs.

Sorry if these changes require a lot of extra effort on your part.

2023-07-23 18:13 UTC, merged